import type {
  BusScheduleDocument,
  BusScheduleRoute,
  CampusLocation,
  ChatMessage,
  ExternalDrive,
  MarketplaceItem,
  PastPaper,
  Profile,
  ProfileReview,
  Question,
  ServiceRequest,
} from "./types";

export const appUser = {
  name: "Aina Rahman",
  role: "UTM Student",
  contactNumber: "+60 12-345 6789",
  matricNumber: "A23CS0123",
  studyYear: "Year 2",
  faculty: "Faculty of Computing",
  age: "21",
  sex: "Female",
  profilePicture: "",
  wallet: 128.4,
};

export const marketplaceCategories = [
  "All",
  "Books",
  "Electronics",
  "Room",
  "Transport",
  "Food",
  "Services",
];

export const marketplaceFilters = [
  "All",
  "Free",
  "Favourites",
  ...marketplaceCategories.filter((category) => category !== "All"),
];

export const campusCategories = [
  "All",
  "Gate",
  "Academic",
  "Student life",
  "Food",
  "Residential",
  "Sports",
  "Services",
];

export const chatChannels = [
  "General",
  "Lost & Found",
  "Assignments",
  "Food",
  "Roommates",
  "Events",
];

export const busScheduleDocuments: BusScheduleDocument[] = [
  {
    id: "regular-2025-2026",
    title: "Campus Shuttle Schedule 2025/2026",
    sourceName: "Jadual Shuttle Kampus Sesi 2025-2026.pdf",
    effective: "Effective 6 October 2025",
    appliesTo: "Regular semester campus shuttle service",
    fileUrl: "/bus-schedules/jadual-shuttle-kampus-sesi-2025-2026.pdf",
    summary:
      "Official UTM shuttle timetable for normal campus movement during the 2025/2026 session.",
    notes: [
      "Use this for daily class movement unless UTM publishes a special schedule.",
      "Students should still check UTMSmart or official UTM channels for sudden operational changes.",
    ],
  },
  {
    id: "semester-break-2026",
    title: "End of Semester 1 Break Shuttle",
    sourceName:
      "Jadual shuttle sepanjang cuti akhir sem 1 sesi 2025_2026 bermula 9_2_2026.pdf",
    effective: "From 9 February 2026",
    appliesTo: "Semester 1 break shuttle operations",
    fileUrl: "/bus-schedules/jadual-shuttle-cuti-akhir-sem-1-2025-2026.pdf",
    summary:
      "Special shuttle timetable for the end of Semester 1 break period in the 2025/2026 session.",
    notes: [
      "Use this only during the listed break period.",
      "Regular semester routes may not follow the same timing during holiday operations.",
    ],
  },
  {
    id: "bdr-tuesday-thursday-2026",
    title: "BDR Tuesday and Thursday Shuttle",
    sourceName: "Jadual Shuttle Sepanjang BDR setiap Selasa dan Khamis 2026.pdf",
    effective: "2026 BDR Tuesdays and Thursdays",
    appliesTo: "BDR schedule days",
    fileUrl: "/bus-schedules/jadual-shuttle-bdr-selasa-khamis-2026.pdf",
    summary:
      "Special shuttle timetable for BDR operations every Tuesday and Thursday in 2026.",
    notes: [
      "Use this when BDR operations are active on Tuesday or Thursday.",
      "The app developer can replace this PDF whenever UTM releases a revised schedule.",
    ],
  },
];

const regularRoutes = [
  ["A1", "KP (U7) to Center Point via Jalan Amal", "KP - CP - Jalan Amal - KP"],
  ["B1", "KP and Kolej 9/10 to Cluster", "KP - K9/10 - T02 - T08 - K9/10 - KP"],
  ["B2", "KP and Kolej 9/10 to Cluster", "KP - K9/10 - T02 - T08 - K9/10 - KP"],
  ["B3", "KP and Kolej 9/10 to Cluster", "KP - K9/10 - T02 - T08 - K9/10 - KP"],
  ["C1", "Kolej 9/10 to Lingkaran Ilmu", "K9/10 - KTC - CP - Jalan Amal - KTC - K9/10"],
  ["C2", "Kolej 9/10 to Lingkaran Ilmu", "K9/10 - KTC - CP - Jalan Amal - KTC - K9/10"],
  ["C3", "Kolej 9/10 to Lingkaran Ilmu", "K9/10 - KTC - CP - Jalan Amal - KTC - K9/10"],
  ["D1", "Center Point to FKT and P19", "CP - N24 - FKT(P29) - P19 - CP"],
  ["E1", "KDOJ, KLG and KDSE to Cluster", "KDOJ - KLG - KDSE - T02/T08"],
  ["E2", "KDOJ, KLG and KDSE to Cluster", "KDOJ - KLG - KDSE - T02/T08"],
  ["E3", "KDOJ, KLG and KDSE to Cluster", "KDOJ - KLG - KDSE - T02/T08"],
  ["E4", "KDOJ, KLG and KDSE to Cluster", "KDOJ - KLG - KDSE - T02/T08"],
  ["E5", "KDOJ, KLG and KDSE to Cluster", "KDOJ - KLG - KDSE - T02/T08"],
  ["E6", "KDOJ to Cluster", "KDOJ - D05 - Jalan Amal - KTC - T02/T08"],
  ["F1", "KTR to Lingkaran Ilmu", "KTR - KTHO - KTDI - Jalan Amal - CP - KTR"],
  ["F2", "KTR to Lingkaran Ilmu", "KTR - KTHO - KTDI - Jalan Amal - CP - KTR"],
  ["G1", "KTR, KTHO and KTDI to FKT", "KTR - KTHO - KTDI - N24 - FKT(P29) - P19 - CP"],
  ["G2", "KTR, KTHO and KTDI to FKT", "KTR - KTHO - KTDI - N24 - FKT(P29) - P19 - CP"],
  ["H", "Center Point to V01 Taman Universiti", "CP - Jalan Amal - V01 - CP"],
  ["J", "Center Point to FABU and Stadium", "Center Point - FABU - Stadium"],
  ["E1 Weekend", "Weekend KDOJ, KLG and KDSE to Kolej 9/10", "KDOJ - KLG - KDSE - Kolej 9/10"],
  ["E2 Weekend", "Weekend KDOJ, KLG and KDSE to Kolej 9/10", "KDOJ - KLG - KDSE - Kolej 9/10"],
] as const;

const breakRoutes = [
  ["B1", "KP and Kolej 9/10 to Cluster", "KP - K9/10 - T02 - T08 - K9/10 - KP"],
  ["B2", "KP and Kolej 9/10 to Cluster", "KP - K9/10 - T02 - T08 - K9/10 - KP"],
  ["B3", "KP and Kolej 9/10 to Cluster", "KP - K9/10 - T02 - T08 - K9/10 - KP"],
  ["C1", "Kolej 9/10 to Lingkaran Ilmu", "K9/10 - KTC - CP - Jalan Amal - KTC - K9/10"],
  ["C2", "Kolej 9/10 to Lingkaran Ilmu", "K9/10 - KTC - CP - Jalan Amal - KTC - K9/10"],
  ["E1", "KDOJ, KLG and KDSE to Cluster", "KDOJ - KLG - KDSE - T02/T08"],
  ["E2", "KDOJ, KLG and KDSE to Cluster", "KDOJ - KLG - KDSE - T02/T08"],
  ["E3", "KDOJ, KLG and KDSE to Cluster", "KDOJ - KLG - KDSE - T02/T08"],
  ["E4", "KDOJ, KLG and KDSE to Cluster", "KDOJ - KLG - KDSE - T02/T08"],
  ["E5", "KDOJ, KLG and KDSE to Cluster", "KDOJ - KLG - KDSE - T02/T08"],
  ["E6", "KDOJ and KLG to Cluster", "KDOJ - KLG - T02/T08"],
  ["E1 Weekend", "Weekend KDOJ, KLG and KDSE to Kolej 9/10", "KDOJ - KLG - KDSE - Kolej 9/10"],
  ["E2 Weekend", "Weekend KDOJ, KLG and KDSE to Kolej 9/10", "KDOJ - KLG - KDSE - Kolej 9/10"],
] as const;

const bdrRoutes = [
  ["A1", "KP (U7) to Center Point via Jalan Amal", "KP - CP - Jalan Amal - KP"],
  ["B1", "KP and Kolej 9/10 to Cluster", "KP - K9/10 - T02 - T08 - K9/10 - KP"],
  ["C1", "Kolej 9/10 to Lingkaran Ilmu", "K9/10 - KTC - CP - Jalan Amal - KTC - K9/10"],
  ["D1", "Center Point to FKT and P19", "CP - N24 - FKT(P29) - P19 - CP"],
  ["E1", "KDOJ, KLG and KDSE to Cluster", "KDOJ - KLG - KDSE - T02/T08"],
  ["E3", "KDOJ, KLG and KDSE to Cluster", "KDOJ - KLG - KDSE - T02/T08"],
  ["E5", "KDOJ to Cluster", "KDOJ - D24 - KTC - T02/T08"],
  ["F1", "KTR to Lingkaran Ilmu", "KTR - KTHO - KTDI - Jalan Amal - CP - KTR"],
  ["G1", "KTR, KTHO and KTDI to FKT", "KTR - KTHO - KTDI - N24 - FKT(P29) - P19 - CP"],
  ["H", "Center Point to V01 Taman Universiti", "CP - Jalan Amal - V01 - CP"],
] as const;

export const busScheduleRoutes: BusScheduleRoute[] = [
  ...regularRoutes.map(([code, route, service], index) => ({
    id: `regular-${index + 1}`,
    documentId: "regular-2025-2026",
    code,
    route,
    service,
    directions: service.split(" - "),
    pageImage: `/bus-schedules/pages/regular-${String(index + 1).padStart(2, "0")}.jpg`,
    pdfPage: index + 1,
    notes: [
      "No service from 12:40 to 14:00 every Friday where stated.",
      "No Saturday, Sunday, public holiday, or semester-break service unless this is a weekend route.",
    ],
  })),
  ...breakRoutes.map(([code, route, service], index) => ({
    id: `break-${index + 1}`,
    documentId: "semester-break-2026",
    code,
    route,
    service,
    directions: service.split(" - "),
    pageImage: `/bus-schedules/pages/break-${String(index + 1).padStart(2, "0")}.jpg`,
    pdfPage: index + 1,
    notes: ["Semester break timetable starting 9 February 2026."],
  })),
  ...bdrRoutes.map(([code, route, service], index) => ({
    id: `bdr-${index + 1}`,
    documentId: "bdr-tuesday-thursday-2026",
    code,
    route,
    service,
    directions: service.split(" - "),
    pageImage: `/bus-schedules/pages/bdr-${String(index + 1).padStart(2, "0")}.jpg`,
    pdfPage: index + 1,
    notes: ["Every Tuesday and Thursday during the active BDR period."],
  })),
];

export const faculties = [
  "All",
  "Azman Hashim International Business School (AHIBS)",
  "Faculty of Artificial Intelligence (FAI)",
  "Faculty of Built Environment and Surveying",
  "Faculty of Chemical & Energy Engineering",
  "Faculty of Computing",
  "Faculty of Educational Sciences and Technology (FEST)",
  "Faculty of Electrical Engineering",
  "Faculty of Management",
  "Faculty of Civil Engineering",
  "Faculty of Mechanical Engineering",
  "Faculty of Science",
  "Faculty of Social Sciences and Humanities",
  "Malaysia-Japan International Institute of Technology (MJIIT)",
];

export const seedProfiles: Profile[] = [
  appUser,
  {
    name: "Hafiz",
    role: "Marketplace seller",
    contactNumber: "+60 11-222 3344",
    matricNumber: "A22CS0456",
    studyYear: "Year 3",
    faculty: "Faculty of Computing",
    age: "22",
    sex: "Male",
    profilePicture: "",
    wallet: 0,
  },
  {
    name: "Mei Lin",
    role: "UTM Student",
    contactNumber: "+60 16-555 8800",
    matricNumber: "A23BE0101",
    studyYear: "Year 2",
    faculty: "Faculty of Built Environment and Surveying",
    age: "21",
    sex: "Female",
    profilePicture: "",
    wallet: 0,
  },
  {
    name: "Kumar",
    role: "Lab project seller",
    contactNumber: "+60 12-888 1234",
    matricNumber: "A21EE0299",
    studyYear: "Year 4",
    faculty: "Faculty of Electrical Engineering",
    age: "23",
    sex: "Male",
    profilePicture: "",
    wallet: 0,
  },
  {
    name: "Farah",
    role: "Community helper",
    contactNumber: "+60 13-909 7788",
    matricNumber: "A23CS0777",
    studyYear: "Year 2",
    faculty: "Faculty of Computing",
    age: "21",
    sex: "Female",
    profilePicture: "",
    wallet: 0,
  },
];

export const seedProfileReviews: ProfileReview[] = [
  {
    id: "review-1",
    profileName: "Hafiz",
    reviewer: "Aina Rahman",
    rating: 5,
    body: "Met at KTR, item matched the listing, and communication was quick.",
    createdAt: "2026-05-12T08:30:00.000Z",
  },
  {
    id: "review-2",
    profileName: "Farah",
    reviewer: "Yusuf",
    rating: 5,
    body: "Helpful answers and very clear with study spot recommendations.",
    createdAt: "2026-05-13T13:10:00.000Z",
  },
];

export const seedMarketplace: MarketplaceItem[] = [
  {
    id: "mkt-1",
    title: "Calculus textbook bundle",
    category: "Books",
    price: 55,
    seller: "Hafiz",
    location: "Kolej Tun Razak",
    fulfillment: "Pickup",
    condition: "Good",
    paymentPreference: "DuitNow QR",
    description: "Thomas Calculus plus tutorial notes. Clean pages, light cover wear.",
    image:
      "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=900&q=80",
    tags: ["math", "foundation", "notes"],
    createdAt: "2026-05-14T09:30:00.000Z",
  },
  {
    id: "mkt-2",
    title: "Mini fridge for hostel",
    category: "Room",
    price: 180,
    seller: "Mei Lin",
    location: "Kolej 9",
    fulfillment: "Pickup",
    condition: "Slightly Used",
    paymentPreference: "Cash",
    description: "Compact fridge, quiet compressor, pickup after finals week.",
    image:
      "https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?auto=format&fit=crop&w=900&q=80",
    tags: ["hostel", "appliance", "pickup"],
    createdAt: "2026-05-13T15:00:00.000Z",
  },
  {
    id: "mkt-3",
    title: "Arduino starter kit",
    category: "Electronics",
    price: 95,
    seller: "Kumar",
    location: "Faculty of Electrical Engineering",
    fulfillment: "Pickup",
    condition: "New",
    paymentPreference: "Bank Transfer",
    description: "Board, sensors, breadboard, jumper wires, and storage box.",
    image:
      "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=900&q=80",
    tags: ["embedded", "project", "lab"],
    createdAt: "2026-05-12T12:45:00.000Z",
  },
  {
    id: "mkt-4",
    title: "Foldable bicycle",
    category: "Transport",
    price: 260,
    seller: "Nabil",
    location: "Dewan Sultan Iskandar",
    fulfillment: "Pickup",
    condition: "Good",
    paymentPreference: "TnG wallet",
    description: "Great for moving between faculties. Includes front light and lock.",
    image:
      "https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&w=900&q=80",
    tags: ["cycle", "campus", "commute"],
    createdAt: "2026-05-11T18:10:00.000Z",
  },
  {
    id: "mkt-5",
    title: "Meal prep nasi ayam set",
    category: "Food",
    price: 8,
    seller: "Dapur Kolej",
    location: "Arked Cengal",
    fulfillment: "Delivery",
    condition: "Fresh",
    paymentPreference: "Cash",
    description: "Lunch preorder. Pickup from 12:30 PM to 2:00 PM.",
    image:
      "https://images.unsplash.com/photo-1569058242567-93de6f36f8eb?auto=format&fit=crop&w=900&q=80",
    tags: ["lunch", "halal", "preorder"],
    createdAt: "2026-05-15T07:20:00.000Z",
  },
  {
    id: "mkt-6",
    title: "Poster design help",
    category: "Services",
    price: 35,
    seller: "Sara",
    location: "PSZ Library",
    fulfillment: "Delivery",
    condition: "Good",
    paymentPreference: "DuitNow QR",
    description: "Research poster, club event poster, and presentation template support.",
    image:
      "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=80",
    tags: ["design", "club", "poster"],
    createdAt: "2026-05-10T11:05:00.000Z",
  },
];

export const campusLocations: CampusLocation[] = [
  {
    id: "loc-main-gate",
    name: "UTM Johor Bahru Main Entrance",
    category: "Gate",
    lat: 1.5567154,
    lng: 103.6368953,
    area: "Skudai",
    blurb: "Main arrival point for the Johor Bahru campus and common pickup landmark.",
    bestFor: ["Grab pickup", "Visitors", "Security"],
  },
  {
    id: "loc-chancellery",
    name: "Sultan Ibrahim Chancellery Building",
    category: "Services",
    lat: 1.558352,
    lng: 103.6384146,
    area: "Central campus",
    blurb: "Administrative landmark used for official university matters and directions.",
    bestFor: ["Administration", "Official visits", "Wayfinding"],
  },
  {
    id: "loc-dsi",
    name: "Dewan Sultan Iskandar",
    category: "Student life",
    lat: 1.5592119,
    lng: 103.6387486,
    area: "Central campus",
    blurb: "Large hall for ceremonies, convocations, exhibitions, and campus events.",
    bestFor: ["Events", "Convocation", "Meetups"],
  },
  {
    id: "loc-mosque",
    name: "Sultan Ismail Mosque",
    category: "Services",
    lat: 1.5592125,
    lng: 103.6376567,
    area: "Lingkaran Ilmu",
    blurb: "Major prayer and community landmark near several academic blocks.",
    bestFor: ["Prayer", "Community", "Landmark"],
  },
  {
    id: "loc-psz",
    name: "Perpustakaan Sultanah Zanariah",
    category: "Student life",
    lat: 1.5594742,
    lng: 103.6369626,
    area: "Central campus",
    blurb: "Main UTM Johor Bahru library branch for study spaces and collections.",
    bestFor: ["Study", "Research", "Printing"],
  },
  {
    id: "loc-przs",
    name: "Perpustakaan Raja Zarith Sofiah",
    category: "Student life",
    lat: 1.5635024,
    lng: 103.65155,
    area: "Central campus",
    blurb: "Library and learning space associated with UTM scholarly resources.",
    bestFor: ["Quiet study", "Resources", "Group work"],
  },
  {
    id: "loc-science",
    name: "Faculty of Science C17",
    category: "Academic",
    lat: 1.5606622,
    lng: 103.6383158,
    area: "Lingkaran Ilmu",
    blurb: "Faculty of Science administrative and teaching area near Sultan Ismail Mosque.",
    bestFor: ["Lectures", "Labs", "Faculty office"],
  },
  {
    id: "loc-computing",
    name: "Faculty of Computing",
    category: "Academic",
    lat: 1.5645359,
    lng: 103.6382387,
    area: "Academic core",
    blurb: "Computing faculty hub for software, AI, data, and information systems students.",
    bestFor: ["Lectures", "Project labs", "Tech clubs"],
  },
  {
    id: "loc-mechanical",
    name: "Faculty of Mechanical Engineering",
    category: "Academic",
    lat: 1.5607169,
    lng: 103.6406933,
    area: "Engineering zone",
    blurb: "Mechanical engineering teaching, labs, offices, and student project areas.",
    bestFor: ["Workshops", "Lectures", "Labs"],
  },
  {
    id: "loc-electrical",
    name: "Faculty of Electrical Engineering",
    category: "Academic",
    lat: 1.5586648,
    lng: 103.6425689,
    area: "Engineering zone",
    blurb: "Electrical and electronic engineering facilities and labs.",
    bestFor: ["Electronics labs", "Lectures", "Projects"],
  },
  {
    id: "loc-civil",
    name: "Faculty of Civil Engineering",
    category: "Academic",
    lat: 1.5633296,
    lng: 103.6361723,
    area: "Engineering zone",
    blurb: "Civil engineering lecture rooms, labs, and built infrastructure learning areas.",
    bestFor: ["Studios", "Labs", "Lectures"],
  },
  {
    id: "loc-chemical",
    name: "Faculty of Chemical & Energy Engineering",
    category: "Academic",
    lat: 1.5655485,
    lng: 103.6399979,
    area: "Engineering zone",
    blurb: "Chemical, energy, and process engineering academic facilities.",
    bestFor: ["Labs", "Research", "Lectures"],
  },
  {
    id: "loc-fabu",
    name: "Faculty of Built Environment and Surveying",
    category: "Academic",
    lat: 1.5588654,
    lng: 103.6355478,
    area: "West campus",
    blurb: "Architecture, planning, surveying, and built environment faculty area.",
    bestFor: ["Studios", "Reviews", "Surveying"],
  },
  {
    id: "loc-scholar",
    name: "Scholar's Inn and UTM International",
    category: "Services",
    lat: 1.5575903,
    lng: 103.6482882,
    area: "Visitor zone",
    blurb: "Visitor accommodation and international-student service landmark.",
    bestFor: ["Visitors", "International office", "Accommodation"],
  },
  {
    id: "loc-health",
    name: "UTM Health Centre",
    category: "Services",
    lat: 1.5595711,
    lng: 103.6273556,
    area: "South campus",
    blurb: "Campus clinic and health support area for students and staff.",
    bestFor: ["Clinic", "Medical support", "Wellness"],
  },
  {
    id: "loc-stadium",
    name: "UTM Stadium",
    category: "Sports",
    lat: 1.5567424,
    lng: 103.6566323,
    area: "Sports zone",
    blurb: "Athletics and big field activities near the sports facilities.",
    bestFor: ["Running", "Matches", "Sports day"],
  },
  {
    id: "loc-sports",
    name: "UTM Sports Centre",
    category: "Sports",
    lat: 1.555442,
    lng: 103.6506884,
    area: "Sports zone",
    blurb: "Indoor and outdoor sports facilities for student recreation.",
    bestFor: ["Badminton", "Fitness", "Training"],
  },
  {
    id: "loc-tasik",
    name: "Tasik Ilmu",
    category: "Student life",
    lat: 1.5567785,
    lng: 103.6351858,
    area: "Central campus",
    blurb: "Green campus lake area used for walks, photos, and calm breaks.",
    bestFor: ["Walking", "Photos", "Breaks"],
  },
  {
    id: "loc-arked-cengal",
    name: "Arked Cengal",
    category: "Food",
    lat: 1.5616122,
    lng: 103.6323068,
    area: "Central campus",
    blurb: "Popular everyday dining and quick-errand stop.",
    bestFor: ["Lunch", "Snacks", "Student errands"],
  },
  {
    id: "loc-arked-meranti",
    name: "Arked Meranti",
    category: "Food",
    lat: 1.5596495,
    lng: 103.6337917,
    area: "Residential edge",
    blurb: "Food and convenience stop near residential colleges.",
    bestFor: ["Dinner", "Groceries", "Meetups"],
  },
  {
    id: "loc-ktdi",
    name: "Kolej Tun Dr Ismail",
    category: "Residential",
    lat: 1.5652469,
    lng: 103.6351218,
    area: "North campus",
    blurb: "Residential college and common student meeting point.",
    bestFor: ["Hostel", "Pickup", "Student life"],
  },
  {
    id: "loc-ktr",
    name: "Kolej Tun Razak",
    category: "Residential",
    lat: 1.5634051,
    lng: 103.6266088,
    area: "Northwest campus",
    blurb: "Residential college area with student facilities and dining access.",
    bestFor: ["Hostel", "Marketplace pickup", "Friends"],
  },
  {
    id: "loc-krp",
    name: "Kolej Rahman Putra",
    category: "Residential",
    lat: 1.5584801,
    lng: 103.6315254,
    area: "North campus",
    blurb: "Residential college used often for pickup and delivery drop-off.",
    bestFor: ["Hostel", "Delivery", "Events"],
  },
  {
    id: "loc-kp",
    name: "Kolej Perdana",
    category: "Residential",
    lat: 1.5565909,
    lng: 103.6479361,
    area: "Northeast campus",
    blurb: "Residential college area close to northern internal roads.",
    bestFor: ["Hostel", "Food orders", "Ride pickup"],
  },
  {
    id: "loc-k9k10",
    name: "Kolej 9 and Kolej 10",
    category: "Residential",
    lat: 1.5602,
    lng: 103.6499,
    area: "East campus",
    blurb: "Residential cluster and frequent student marketplace meeting point.",
    bestFor: ["Hostel", "Pickup", "Deliveries"],
  },
  {
    id: "loc-kdse",
    name: "Kolej Datin Seri Endon",
    category: "Residential",
    lat: 1.5666707,
    lng: 103.6265161,
    area: "East campus",
    blurb: "Residential college at the eastern side of the campus.",
    bestFor: ["Hostel", "Ride pickup", "Student life"],
  },
  { id: "loc-added-restoran-al-safa-taman-universiti-01", name: "Restoran Al-Safa • Taman Universiti", category: "Food", lat: 1.5446111, lng: 103.6291989, area: "UTM nearby dining", blurb: "Restoran Al-Safa • Taman Universiti is a food and cafe stop near UTM for meals, meetups, delivery pickup, and student hangouts.", bestFor: ["Meals", "Meetups", "Student stop"] },
  { id: "loc-added-aeon-taman-universiti-shopping-centre-02", name: "AEON Taman Universiti Shopping Centre", category: "Student life", lat: 1.5427763, lng: 103.6291529, area: "Johor Bahru student stop", blurb: "AEON Taman Universiti Shopping Centre is a shopping and errands destination for supplies, groceries, food, and weekend trips from UTM.", bestFor: ["Shopping", "Errands", "Weekend trip"] },
  { id: "loc-added-eco-shop-03", name: "Eco Shop", category: "Student life", lat: 1.5437069, lng: 103.6302488, area: "Johor Bahru student stop", blurb: "Eco Shop is a shopping and errands destination for supplies, groceries, food, and weekend trips from UTM.", bestFor: ["Shopping", "Errands", "Weekend trip"] },
  { id: "loc-added-v01-utm-04", name: "V01 UTM", category: "Services", lat: 1.544305, lng: 103.6325634, area: "UTM nearby service", blurb: "V01 UTM is a useful service landmark for campus errands, transport planning, and student support around UTM.", bestFor: ["Errands", "Transport", "Student support"] },
  { id: "loc-added-maybank-taman-universiti-skudai-05", name: "Maybank (Taman Universiti, Skudai)", category: "Services", lat: 1.5424737, lng: 103.6305052, area: "UTM nearby service", blurb: "Maybank (Taman Universiti, Skudai) is a nearby banking stop for ATM, account, and payment errands around the UTM area.", bestFor: ["Errands", "Transport", "Student support"] },
  { id: "loc-added-thefitlab-gym-06", name: "THEFITLAB GYM", category: "Sports", lat: 1.5425246, lng: 103.6315807, area: "UTM nearby recreation", blurb: "THEFITLAB GYM is a recreation stop for workouts, sports, movies, and casual trips around Johor Bahru.", bestFor: ["Fitness", "Recreation", "Meetups"] },
  { id: "loc-added-xtreme-fitness-07", name: "Xtreme Fitness", category: "Sports", lat: 1.5401029, lng: 103.6288181, area: "UTM nearby recreation", blurb: "Xtreme Fitness is a recreation stop for workouts, sports, movies, and casual trips around Johor Bahru.", bestFor: ["Fitness", "Recreation", "Meetups"] },
  { id: "loc-added-belad-al-rafidain-08", name: "Belad Al-Rafidain", category: "Food", lat: 1.545089, lng: 103.6291952, area: "UTM nearby dining", blurb: "Belad Al-Rafidain is a food and cafe stop near UTM for meals, meetups, delivery pickup, and student hangouts.", bestFor: ["Meals", "Meetups", "Student stop"] },
  { id: "loc-added-melana-apartment-09", name: "Melana Apartment", category: "Residential", lat: 1.545211, lng: 103.6272418, area: "UTM nearby housing", blurb: "Melana Apartment is a residential or accommodation landmark for ride pickup, drop-off, delivery, and student housing navigation.", bestFor: ["Housing", "Pickup", "Drop-off"] },
  { id: "loc-added-melawis-apartment-taman-universiti-813-10", name: "Melawis Apartment, Taman Universiti, 81300 Johor Bahru, Johor Darul Ta'zim", category: "Residential", lat: 1.5439665, lng: 103.6288329, area: "UTM nearby housing", blurb: "Melawis Apartment, Taman Universiti, 81300 Johor Bahru, Johor Darul Ta'zim is a residential or accommodation landmark for ride pickup, drop-off, delivery, and student housing navigation.", bestFor: ["Housing", "Pickup", "Drop-off"] },
  { id: "loc-added-the-garden-residences-11", name: "The Garden Residences", category: "Residential", lat: 1.5143853, lng: 103.6291945, area: "UTM nearby housing", blurb: "The Garden Residences is a residential or accommodation landmark for ride pickup, drop-off, delivery, and student housing navigation.", bestFor: ["Housing", "Pickup", "Drop-off"] },
  { id: "loc-added-desa-skudai-apartment-12", name: "Desa Skudai Apartment", category: "Residential", lat: 1.5365284, lng: 103.6351349, area: "UTM nearby housing", blurb: "Desa Skudai Apartment is a residential or accommodation landmark for ride pickup, drop-off, delivery, and student housing navigation.", bestFor: ["Housing", "Pickup", "Drop-off"] },
  { id: "loc-added-surau-an-nur-jalan-sejahtera-17-13", name: "Surau An Nur Jalan Sejahtera 17", category: "Services", lat: 1.5388859, lng: 103.6341522, area: "UTM nearby service", blurb: "Surau An Nur Jalan Sejahtera 17 is a useful service landmark for campus errands, transport planning, and student support around UTM.", bestFor: ["Errands", "Transport", "Student support"] },
  { id: "loc-added-u-mall-14", name: "U Mall", category: "Student life", lat: 1.5468943, lng: 103.6222994, area: "Johor Bahru student stop", blurb: "U Mall is a shopping and errands destination for supplies, groceries, food, and weekend trips from UTM.", bestFor: ["Shopping", "Errands", "Weekend trip"] },
  { id: "loc-added-d-summit-residences-15", name: "D'Summit Residences", category: "Residential", lat: 1.5488812, lng: 103.7065786, area: "UTM nearby housing", blurb: "D'Summit Residences is a residential or accommodation landmark for ride pickup, drop-off, delivery, and student housing navigation.", bestFor: ["Housing", "Pickup", "Drop-off"] },
  { id: "loc-added-klg-campus-residence-16", name: "KLG Campus Residence", category: "Residential", lat: 1.571635, lng: 103.6209618, area: "UTM nearby housing", blurb: "KLG Campus Residence is a residential or accommodation landmark for ride pickup, drop-off, delivery, and student housing navigation.", bestFor: ["Housing", "Pickup", "Drop-off"] },
  { id: "loc-added-kolej-dato-onn-jaafar-17", name: "Kolej Dato Onn Jaafar", category: "Residential", lat: 1.5761039, lng: 103.6209947, area: "UTM nearby housing", blurb: "Kolej Dato Onn Jaafar is a residential or accommodation landmark for ride pickup, drop-off, delivery, and student housing navigation.", bestFor: ["Housing", "Pickup", "Drop-off"] },
  { id: "loc-added-masjid-taman-sri-pulai-18", name: "Masjid Taman Sri Pulai", category: "Services", lat: 1.5638344, lng: 103.617437, area: "UTM nearby service", blurb: "Masjid Taman Sri Pulai is a useful service landmark for campus errands, transport planning, and student support around UTM.", bestFor: ["Errands", "Transport", "Student support"] },
  { id: "loc-added-daiman-sri-skudai-sports-center-19", name: "Daiman Sri Skudai Sports Center", category: "Sports", lat: 1.5461517, lng: 103.6554191, area: "UTM nearby recreation", blurb: "Daiman Sri Skudai Sports Center is a recreation stop for workouts, sports, movies, and casual trips around Johor Bahru.", bestFor: ["Fitness", "Recreation", "Meetups"] },
  { id: "loc-added-ksl-d-secret-garden-20", name: "KSL D'Secret Garden", category: "Residential", lat: 1.5531353, lng: 103.713162, area: "UTM nearby housing", blurb: "KSL D'Secret Garden is a residential or accommodation landmark for ride pickup, drop-off, delivery, and student housing navigation.", bestFor: ["Housing", "Pickup", "Drop-off"] },
  { id: "loc-added-paradigm-mall-johor-bahru-21", name: "Paradigm Mall Johor Bahru", category: "Student life", lat: 1.5156318, lng: 103.6857437, area: "Johor Bahru student stop", blurb: "Paradigm Mall Johor Bahru is a shopping and errands destination for supplies, groceries, food, and weekend trips from UTM.", bestFor: ["Shopping", "Errands", "Weekend trip"] },
  { id: "loc-added-the-mall-mid-valley-southkey-22", name: "The Mall, Mid Valley Southkey", category: "Student life", lat: 1.5013338, lng: 103.7774187, area: "Johor Bahru student stop", blurb: "The Mall, Mid Valley Southkey is a shopping and errands destination for supplies, groceries, food, and weekend trips from UTM.", bestFor: ["Shopping", "Errands", "Weekend trip"] },
  { id: "loc-added-aeon-tebrau-city-shopping-centre-3-per-23", name: "Aeon Tebrau City Shopping Centre, 3, Persiaran Desa Tebrau, Taman Desa Tebrau, 81100 Johor Bahru, Johor Darul Ta'zim", category: "Student life", lat: 1.5490688, lng: 103.7959073, area: "Johor Bahru student stop", blurb: "Aeon Tebrau City Shopping Centre, 3, Persiaran Desa Tebrau, Taman Desa Tebrau, 81100 Johor Bahru, Johor Darul Ta'zim is a shopping and errands destination for supplies, groceries, food, and weekend trips from UTM.", bestFor: ["Shopping", "Errands", "Weekend trip"] },
  { id: "loc-added-tgv-24", name: "TGV", category: "Sports", lat: 1.5499352, lng: 103.7956583, area: "UTM nearby recreation", blurb: "TGV is a recreation stop for workouts, sports, movies, and casual trips around Johor Bahru.", bestFor: ["Fitness", "Recreation", "Meetups"] },
  { id: "loc-added-sultan-ismail-hospital-25", name: "Sultan Ismail Hospital", category: "Services", lat: 1.5462801, lng: 103.7908921, area: "UTM nearby service", blurb: "Sultan Ismail Hospital is an important healthcare landmark for medical visits, emergency planning, and transport requests.", bestFor: ["Errands", "Transport", "Student support"] },
  { id: "loc-added-ikea-tebrau-26", name: "IKEA Tebrau", category: "Student life", lat: 1.5515208, lng: 103.7988581, area: "Johor Bahru student stop", blurb: "IKEA Tebrau is a shopping and errands destination for supplies, groceries, food, and weekend trips from UTM.", bestFor: ["Shopping", "Errands", "Weekend trip"] },
  { id: "loc-added-toppen-shopping-centre-27", name: "Toppen Shopping Centre", category: "Student life", lat: 1.5516285, lng: 103.7980674, area: "Johor Bahru student stop", blurb: "Toppen Shopping Centre is a shopping and errands destination for supplies, groceries, food, and weekend trips from UTM.", bestFor: ["Shopping", "Errands", "Weekend trip"] },
  { id: "loc-added-nsk-trade-city-pandan-johor-bahru-28", name: "NSK Trade City Pandan Johor Bahru", category: "Student life", lat: 1.5366845, lng: 103.7846037, area: "Johor Bahru student stop", blurb: "NSK Trade City Pandan Johor Bahru is a student-life destination for errands, shopping, supplies, and weekend movement from UTM.", bestFor: ["Shopping", "Errands", "Weekend trip"] },
  { id: "loc-added-ksl-city-mall-29", name: "KSL City Mall", category: "Student life", lat: 1.4858456, lng: 103.762422, area: "Johor Bahru student stop", blurb: "KSL City Mall is a shopping and errands destination for supplies, groceries, food, and weekend trips from UTM.", bestFor: ["Shopping", "Errands", "Weekend trip"] },
  { id: "loc-added-plaza-pelangi-30", name: "Plaza Pelangi", category: "Student life", lat: 1.4804916, lng: 103.7651672, area: "Johor Bahru student stop", blurb: "Plaza Pelangi is a student-life destination for errands, shopping, supplies, and weekend movement from UTM.", bestFor: ["Shopping", "Errands", "Weekend trip"] },
  { id: "loc-added-johor-bahru-city-square-31", name: "Johor Bahru City Square", category: "Services", lat: 1.4616534, lng: 103.7638662, area: "UTM nearby service", blurb: "Johor Bahru City Square is a shopping and errands destination for supplies, groceries, food, and weekend trips from UTM.", bestFor: ["Errands", "Transport", "Student support"] },
  { id: "loc-added-randf-mall-32", name: "R&F Mall", category: "Student life", lat: 1.458603, lng: 103.7685951, area: "Johor Bahru student stop", blurb: "R&F Mall is a shopping and errands destination for supplies, groceries, food, and weekend trips from UTM.", bestFor: ["Shopping", "Errands", "Weekend trip"] },
  { id: "loc-added-johor-zoo-33", name: "Johor Zoo", category: "Student life", lat: 1.4575382, lng: 103.7521843, area: "Johor Bahru student stop", blurb: "Johor Zoo is a student-life destination for errands, shopping, supplies, and weekend movement from UTM.", bestFor: ["Shopping", "Errands", "Weekend trip"] },
  { id: "loc-added-sultanah-aminah-hospital-johor-bahru-34", name: "Sultanah Aminah Hospital, Johor Bahru", category: "Services", lat: 1.4584962, lng: 103.7460342, area: "UTM nearby service", blurb: "Sultanah Aminah Hospital, Johor Bahru is an important healthcare landmark for medical visits, emergency planning, and transport requests.", bestFor: ["Errands", "Transport", "Student support"] },
  { id: "loc-added-country-garden-danga-bay-35", name: "Country Garden Danga Bay", category: "Residential", lat: 1.4643569, lng: 103.7270267, area: "UTM nearby housing", blurb: "Country Garden Danga Bay is a residential or accommodation landmark for ride pickup, drop-off, delivery, and student housing navigation.", bestFor: ["Housing", "Pickup", "Drop-off"] },
  { id: "loc-added-kings-bay-country-garden-36", name: "Kings Bay Country Garden ", category: "Residential", lat: 1.4625248, lng: 103.7289512, area: "UTM nearby housing", blurb: "Kings Bay Country Garden  is a residential or accommodation landmark for ride pickup, drop-off, delivery, and student housing navigation.", bestFor: ["Housing", "Pickup", "Drop-off"] },
  { id: "loc-added-b5-johor-street-market-37", name: "B5 Johor Street Market", category: "Student life", lat: 1.4966073, lng: 103.704153, area: "Johor Bahru student stop", blurb: "B5 Johor Street Market is a student-life destination for errands, shopping, supplies, and weekend movement from UTM.", bestFor: ["Shopping", "Errands", "Weekend trip"] },
  { id: "loc-added-kipmall-tampoi-38", name: "KIPMall Tampoi", category: "Student life", lat: 1.5087579, lng: 103.6872425, area: "Johor Bahru student stop", blurb: "KIPMall Tampoi is a shopping and errands destination for supplies, groceries, food, and weekend trips from UTM.", bestFor: ["Shopping", "Errands", "Weekend trip"] },
  { id: "loc-added-rhb-bank-taman-ungku-tun-aminah-39", name: "RHB Bank - Taman Ungku Tun Aminah", category: "Services", lat: 1.5288986, lng: 103.6647589, area: "UTM nearby service", blurb: "RHB Bank - Taman Ungku Tun Aminah is a nearby banking stop for ATM, account, and payment errands around the UTM area.", bestFor: ["Errands", "Transport", "Student support"] },
  { id: "loc-added-mydin-mall-mutiara-rini-40", name: "Mydin Mall Mutiara Rini", category: "Student life", lat: 1.515083, lng: 103.6354573, area: "Johor Bahru student stop", blurb: "Mydin Mall Mutiara Rini is a shopping and errands destination for supplies, groceries, food, and weekend trips from UTM.", bestFor: ["Shopping", "Errands", "Weekend trip"] },
  { id: "loc-added-gsc-paradigm-jb-41", name: "GSC Paradigm JB", category: "Sports", lat: 1.5160239, lng: 103.6853703, area: "UTM nearby recreation", blurb: "GSC Paradigm JB is a recreation stop for workouts, sports, movies, and casual trips around Johor Bahru.", bestFor: ["Fitness", "Recreation", "Meetups"] },
  { id: "loc-added-restoran-nisha-fattah-42", name: "Restoran Nisha Fattah", category: "Food", lat: 1.5441836, lng: 103.6297766, area: "UTM nearby dining", blurb: "Restoran Nisha Fattah is a food and cafe stop near UTM for meals, meetups, delivery pickup, and student hangouts.", bestFor: ["Meals", "Meetups", "Student stop"] },
  { id: "loc-added-al-nawras-yemen-restaurant-43", name: "Al-Nawras Yemen Restaurant", category: "Food", lat: 1.5518952, lng: 103.6249987, area: "UTM nearby dining", blurb: "Al-Nawras Yemen Restaurant is a food and cafe stop near UTM for meals, meetups, delivery pickup, and student hangouts.", bestFor: ["Meals", "Meetups", "Student stop"] },
  { id: "loc-added-flora-ville-44", name: "Flora Ville", category: "Residential", lat: 1.5532855, lng: 103.6207653, area: "UTM nearby housing", blurb: "Flora Ville is a residential or accommodation landmark for ride pickup, drop-off, delivery, and student housing navigation.", bestFor: ["Housing", "Pickup", "Drop-off"] },
  { id: "loc-added-pulai-springs-resort-johor-bahru-resor-45", name: "Pulai Springs Resort, Johor Bahru (Resort Hotel)", category: "Services", lat: 1.5547632, lng: 103.6138915, area: "UTM nearby service", blurb: "Pulai Springs Resort, Johor Bahru (Resort Hotel) is a useful service landmark for campus errands, transport planning, and student support around UTM.", bestFor: ["Errands", "Transport", "Student support"] },
  { id: "loc-added-econsave-taman-teratai-hypermarket-who-46", name: "Econsave Taman Teratai (Hypermarket | Wholesale)", category: "Student life", lat: 1.5671634, lng: 103.611686, area: "Johor Bahru student stop", blurb: "Econsave Taman Teratai (Hypermarket | Wholesale) is a shopping and errands destination for supplies, groceries, food, and weekend trips from UTM.", bestFor: ["Shopping", "Errands", "Weekend trip"] },
  { id: "loc-added-golf-ground-driving-range-47", name: "Golf Ground Driving Range", category: "Sports", lat: 1.5528715, lng: 103.6302115, area: "UTM nearby recreation", blurb: "Golf Ground Driving Range is a recreation stop for workouts, sports, movies, and casual trips around Johor Bahru.", bestFor: ["Fitness", "Recreation", "Meetups"] },
  { id: "loc-added-24-hour-study-room-utm-48", name: "24-Hour Study Room, UTM", category: "Services", lat: 1.5590498, lng: 103.6367426, area: "UTM nearby service", blurb: "24-Hour Study Room, UTM is an on-campus study landmark for late-night study plans, meetups, and transport pickup.", bestFor: ["Errands", "Transport", "Student support"] },
  { id: "loc-added-he-and-she-coffee-utm-johor-49", name: "He & She Coffee UTM JOHOR", category: "Food", lat: 1.5598008, lng: 103.6372777, area: "UTM nearby dining", blurb: "He & She Coffee UTM JOHOR is a food and cafe stop near UTM for meals, meetups, delivery pickup, and student hangouts.", bestFor: ["Meals", "Meetups", "Student stop"] },
  { id: "loc-added-ezz-one-western-food-50", name: "Ezz One western food", category: "Food", lat: 1.5598062, lng: 103.6336336, area: "UTM nearby dining", blurb: "Ezz One western food is a food and cafe stop near UTM for meals, meetups, delivery pickup, and student hangouts.", bestFor: ["Meals", "Meetups", "Student stop"] },
  { id: "loc-added-lemon-tree-utm-51", name: "Lemon Tree UTM", category: "Food", lat: 1.5596467, lng: 103.6339085, area: "UTM nearby dining", blurb: "Lemon Tree UTM is a food and cafe stop near UTM for meals, meetups, delivery pickup, and student hangouts.", bestFor: ["Meals", "Meetups", "Student stop"] },
  { id: "loc-added-richiamo-coffee-utm-skudai-52", name: "Richiamo Coffee - UTM Skudai", category: "Food", lat: 1.5596232, lng: 103.633532, area: "UTM nearby dining", blurb: "Richiamo Coffee - UTM Skudai is a food and cafe stop near UTM for meals, meetups, delivery pickup, and student hangouts.", bestFor: ["Meals", "Meetups", "Student stop"] },
  { id: "loc-added-zus-coffee-taman-universiti-skudai-53", name: "ZUS Coffee - Taman Universiti, Skudai", category: "Food", lat: 1.5438835, lng: 103.6304153, area: "UTM nearby dining", blurb: "ZUS Coffee - Taman Universiti, Skudai is a food and cafe stop near UTM for meals, meetups, delivery pickup, and student hangouts.", bestFor: ["Meals", "Meetups", "Student stop"] },
  { id: "loc-added-zus-coffee-universiti-teknologi-malays-54", name: "ZUS Coffee - Universiti Teknologi Malaysia (Arked Meranti)", category: "Food", lat: 1.5597731, lng: 103.6337336, area: "UTM nearby dining", blurb: "ZUS Coffee - Universiti Teknologi Malaysia (Arked Meranti) is a food and cafe stop near UTM for meals, meetups, delivery pickup, and student hangouts.", bestFor: ["Meals", "Meetups", "Student stop"] },
  { id: "loc-added-center-point-55", name: "Center Point", category: "Services", lat: 1.559693, lng: 103.634748, area: "UTM nearby service", blurb: "Center Point is a central UTM student landmark for services, meetups, events, and campus navigation.", bestFor: ["Errands", "Transport", "Student support"] },
  { id: "loc-added-student-union-building-sub-56", name: "Student Union Building (SUB)", category: "Services", lat: 1.5587823, lng: 103.639482, area: "UTM nearby service", blurb: "Student Union Building (SUB) is a central UTM student landmark for services, meetups, events, and campus navigation.", bestFor: ["Errands", "Transport", "Student support"] },
  { id: "loc-added-tun-aminah-bus-station-57", name: "Tun Aminah Bus Station", category: "Services", lat: 1.5206491, lng: 103.6611926, area: "UTM nearby service", blurb: "Tun Aminah Bus Station is a major public transport hub for bus, rail, city transfer, and outstation travel from UTM.", bestFor: ["Errands", "Transport", "Student support"] },
  { id: "loc-added-larkin-sentral-58", name: "Larkin Sentral", category: "Services", lat: 1.4955553, lng: 103.7417018, area: "UTM nearby service", blurb: "Larkin Sentral is a major public transport hub for bus, rail, city transfer, and outstation travel from UTM.", bestFor: ["Errands", "Transport", "Student support"] },
  { id: "loc-added-jb-sentral-80300-johor-bahru-johor-dar-59", name: "Jb Sentral, 80300 Johor Bahru, Johor Darul Ta'zim", category: "Services", lat: 1.4632467, lng: 103.7645805, area: "UTM nearby service", blurb: "Jb Sentral, 80300 Johor Bahru, Johor Darul Ta'zim is a major public transport hub for bus, rail, city transfer, and outstation travel from UTM.", bestFor: ["Errands", "Transport", "Student support"] },
  { id: "loc-added-johor-bahru-senai-international-airpor-60", name: "Johor Bahru Senai International Airport", category: "Services", lat: 1.635894, lng: 103.6679273, area: "UTM nearby service", blurb: "Johor Bahru Senai International Airport is the main airport option for UTM students planning flights, airport rides, or luggage pickup.", bestFor: ["Errands", "Transport", "Student support"] },
];

export const seedMessages: ChatMessage[] = [
  {
    id: "msg-1",
    channel: "General",
    author: "Aqil",
    authorAvatar: "",
    content: "Anyone going to DSI tonight for the tech talk?",
    time: "2026-05-15T10:05:00.000Z",
  },
  {
    id: "msg-2",
    channel: "Lost & Found",
    author: "Jia",
    authorAvatar: "",
    content: "Found a black bottle near PSZ. I left it at the counter.",
    time: "2026-05-15T10:20:00.000Z",
  },
  {
    id: "msg-3",
    channel: "Assignments",
    author: "Amir",
    authorAvatar: "",
    content: "SECI2143 group wants one more member for the mini project.",
    time: "2026-05-15T11:12:00.000Z",
  },
  {
    id: "msg-4",
    channel: "Food",
    author: "Nora",
    authorAvatar: "",
    content: "Arked Cengal ayam penyet queue is short right now.",
    time: "2026-05-15T12:35:00.000Z",
  },
];

export const seedQuestions: Question[] = [
  {
    id: "q-1",
    title: "Best quiet study spots after 8 PM?",
    body: "PSZ gets packed during revision week. Any calm alternatives around central campus?",
    author: "Farah",
    authorAvatar: "",
    tags: ["study", "library", "night"],
    votes: 18,
    resolved: false,
    answers: [
      {
        id: "a-1",
        author: "Yusuf",
        authorAvatar: "",
        body: "Try the upper levels of PRZS first, then faculty common rooms if your building stays open.",
        helpful: 9,
        helpfulBy: [],
        time: "2026-05-13T20:10:00.000Z",
      },
    ],
  },
  {
    id: "q-2",
    title: "How early should I book a driver to Senai Airport?",
    body: "Morning flight from Senai. I am staying around Kolej 10.",
    author: "Daniel",
    authorAvatar: "",
    tags: ["airport", "transport"],
    votes: 11,
    resolved: true,
    answers: [
      {
        id: "a-2",
        author: "Aina",
        authorAvatar: "",
        body: "For morning flights, book the night before and leave buffer for campus gate traffic.",
        helpful: 14,
        helpfulBy: [],
        time: "2026-05-12T09:00:00.000Z",
      },
    ],
  },
];

export const seedPapers: PastPaper[] = [
  {
    id: "paper-1",
    code: "SECJ1013",
    title: "Programming Technique I Final",
    faculty: "Faculty of Computing",
    year: "2025",
    semester: "Semester 1",
    type: "Final",
    uploader: "Aina",
    fileName: "SECJ1013-final-2025.pdf",
    fileSize: "1.8 MB",
    status: "Approved",
    downloads: 74,
  },
  {
    id: "paper-2",
    code: "SECI2143",
    title: "Probability and Statistical Data Analysis",
    faculty: "Faculty of Computing",
    year: "2024",
    semester: "Semester 2",
    type: "Test 1",
    uploader: "Kumar",
    fileName: "SECI2143-midterm-2024.pdf",
    fileSize: "940 KB",
    status: "Approved",
    downloads: 51,
  },
  {
    id: "paper-3",
    code: "SKMM2313",
    title: "Thermodynamics Past Year Questions",
    faculty: "Faculty of Mechanical Engineering",
    year: "2025",
    semester: "Semester 2",
    type: "Final",
    uploader: "Nabil",
    fileName: "SKMM2313-final-2025.pdf",
    fileSize: "2.4 MB",
    status: "Approved",
    downloads: 63,
  },
];

export const externalDrives: ExternalDrive[] = [
  {
    id: "drive-teoh-chee-jin",
    name: "Teoh Chee Jin Drive",
    owner: "Teoh Chee Jin",
    url: "https://drive.google.com/drive/folders/1Ztm-qPtT60e_eg9QHCrUTE_RC1ovVh93?usp=drive_link",
    description: "Community drive for past papers and academic resources.",
  },
  {
    id: "drive-ysag",
    name: "YSAG Drive",
    owner: "YSAG",
    url: "https://drive.google.com/drive/folders/1EcPzK0iiME7xpzVKF7v2lTEDlnsvR2pb?usp=drive_link",
    description: "Shared student drive with organized study materials.",
  },
  {
    id: "drive-iss-egypt",
    name: "ISS Egypt Drive",
    owner: "ISS Egypt",
    url: "https://drive.google.com/drive/folders/1BJg71GTYRuo8Ssy8TbhGmdEVjg2VDaH8",
    description: "International student society drive for Egypt community resources.",
  },
  {
    id: "drive-iss-sudan",
    name: "ISS Sudan Drive",
    owner: "ISS Sudan",
    url: "https://drive.google.com/drive/folders/1NGUujf6VnutrGamXpMVVguFF2LGWPVQn?usp=drive_link",
    description: "International student society drive for Sudan community resources.",
  },
  {
    id: "drive-mbs",
    name: "MBS Drive",
    owner: "MBS",
    url: "https://drive.google.com/drive/folders/1NPMbFl2HRjCQLKEuJgL5uM8mvWJk7BZN?usp=drive_link",
    description: "Student-maintained drive for course files and exam prep.",
  },
];

export const seedRequests: ServiceRequest[] = [
  {
    id: "req-1",
    type: "Ride",
    title: "Ride to Paradigm Mall",
    requester: "Aina",
    pickup: "Kolej Perdana",
    dropoff: "Paradigm Mall Johor Bahru",
    schedule: "Today, 6:30 PM",
    budget: 18,
    paymentPreference: "TnG wallet",
    notes: "Two passengers with one small bag.",
    status: "Open",
  },
  {
    id: "req-2",
    type: "Delivery",
    title: "Collect printing from PSZ",
    requester: "Farah",
    pickup: "PSZ Library",
    dropoff: "Kolej Tun Dr Ismail",
    schedule: "Today, 3:00 PM",
    budget: 7,
    paymentPreference: "Cash",
    notes: "Paid printout at counter, just need pickup.",
    status: "Matched",
    driver: "Hakim",
  },
];

